name: Nightly Build

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Services with Docker Compose
        run: docker compose up -d  

      - name: Wait for Database to be Ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec $(docker ps -q -f name=db) psql -U postgres -c "SELECT 1"; do
            echo "Waiting for database..."
            sleep 5
          done
          echo "Database is ready!"

      - name: Run Database Migrations
        run: docker exec $(docker ps -q -f name=web) alembic upgrade head

      - name: Run Tests Inside Docker
        run: docker exec $(docker ps -q -f name=web) pytest
        continue-on-error: false  

      - name: Stop Docker Services
        run: docker compose down  

      - name: Build and Push Docker Image
        if: success()  
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud:latest ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud:$(date +%Y%m%d)
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud:$(date +%Y%m%d)

  notify-on-failure:
    needs: build-and-test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: marcelle.vonrueden72@ethereal.email
          password: Z75RUTaWnGs2ytv7bX
          from: "no-reply@your-repo.com"
          to: tlin52@dons.usfca.edu
          subject: "❌ nightly build fail"
          body: |
            In the repository ${{ github.repository }} was Fail. 
